### ISSUE TITLE
Publish on new entry page

### ISSUE THREAD

**Issue by jude86-7** [pixelninja/publishbutton#2]
Hi, thanks for the great extension, I'm finding it really useful.
Just wondering if there is an option to set a new entry to 'unpublished' when creating it. Currently on my 'create new' page there is no option to publish/unpublish, this only appears after the entry has been saved.
It would be useful to add unpublished entries without having to go in and edit?
Many thanks

**Comment by pixelninja** [comment]
Hi! There sure is :)

The checkbox `Checked by default` handles this. If it's checked, entries will be published automatically, if it's unchecked, entries won't be published.

Happy holidays!
